from django.contrib import admin
from .models import *
from django.db import models
admin.site.register( School )
admin.site.register( Teacher )
admin.site.register( TransferTeacher )
admin.site.register( Product )
admin.site.register( Deo )
admin.site.register( TransferDeo )
admin.site.register( District )
admin.site.register( Region )
admin.site.register( Access )
admin.site.register( Ownership )
admin.site.register( Schtype )
admin.site.register( Category )
admin.site.register( Cennostatus )
admin.site.register( Level )
admin.site.register( Regstatus )
admin.site.register( Section )
admin.site.register( Designation )
admin.site.register( FacilityStatus )
admin.site.register( FacilityType )
admin.site.register( Gender )
admin.site.register( TeacherStatus )
admin.site.register( ResourceSource )
admin.site.register( ResourceType )
admin.site.register( Resource )
admin.site.register( Facility )
admin.site.register( AllocateResource )
admin.site.register( ProductStatus )
admin.site.register( ProductVote )