from django.urls import path
from .views import *
from . import views

urlpatterns = [
    # Home related urls-----------------------------------------------------------------------------
    path('upload_district/', DistrictUploadView.as_view(), name='upload_district' ),
    path('upload_county/', CountyUploadView.as_view(), name='upload_county' ),
    path('upload_subcounty/', SubCountyUploadView.as_view(), name='upload_subcounty' ),
    path('upload_parish/', ParishUploadView.as_view(), name='upload_parish' ),
    path('upload_school/', SchoolUploadView.as_view(), name='upload_school' ),
    path('upload_secondary_school/', SecondarySchoolUploadView.as_view(), name='upload_secondary_school' ),
    path('upload_tertiary_school/', TertiarySchoolUploadView.as_view(), name='upload_tertiary_school' ),
    path('', views.home, name='ministry-home'),
    path('schools_in_region_chart/<int:pk>/', views.schools_region_chart, name='schools-in-region-chart'),
    path('schools_in_year_chart/<int:pk>/', views.schools_year_chart, name='schools-in-year-chart'),
    path('operation_status_chart/<int:pk>/', views.operation_status_chart, name='operation-status-chart'),
    path('founder_chart/<int:pk>/', views.founder_chart, name='founder-chart'),
    path('funder_chart/<int:pk>/', views.funder_chart, name='funder-chart'),
    path('category_chart/<int:pk>/', views.category_chart, name='category-chart'),
    path('section_chart/<int:pk>/', views.section_chart, name='section-chart'),
    path('registry_chart/<int:pk>/', views.registry_status_chart, name='registry-status-chart'),
    path('rural_urban_chart/<int:pk>/', views.rural_urban_chart, name='rural-urban-chart'),
    path('access_chart/<int:pk>/', views.access_chart, name='access-chart'),
    path('nearest_school_chart/<int:pk>/', views.nearest_school_chart, name='nearest-school-chart'),
    path('deo_office_chart/<int:pk>/', views.deo_office_chart, name='deo-office-chart'),
    path('pie-chart/', views.pie_chart, name='pie-chart'),
    # Student's Tab ----------------------------------------------------------------------------
    path('students/<int:pk>/repeaters/', views.repeaters, name='repeaters'),
    path('students/<int:pk>/nationality/', views.nationality, name='nationality'),
    path('students/<int:pk>/physical_streams/', views.physical_streams, name='physical-streams'),
    path('students/<int:pk>/orphans/', views.orphans, name='orphans'),
    path('students/<int:pk>/special_needs/', views.special_needs, name='special-needs'),
    path('students/<int:pk>/seating_and_writing_space/', views.seating_and_writing_space, name='seating-and-writing-space'),
    path('students/<int:pk>/transfered_students/', views.transfered_students, name='transfered-students'),
    path('students/<int:pk>/examinations/', views.examinations, name='examinations'),
    path('students/<int:pk>/proposed_intake/', views.proposed_intake, name='proposed-intake'),
    path('students/<int:pk>/new_entrants/', views.new_entrants, name='new-entrants'),
    path('students/<int:pk>/enrolments/', views.enrolments, name='enrolments'),
    path('ministry_add_students/<int:pk>/enrolments/', views.ministry_add_students, name='ministry-add-students'),
    # School related urls-----------------------------------------------------------------------------
    path('schools/<int:pk>/district', views.view_schools, name='schools'),
    path('schools/<int:pk>/op_status', views.operation_status, name='operation-status'),
    path('schools/<int:pk>/founder', views.founder, name='founder'),
    path('schools/<int:pk>/funder', views.funders, name='funder'),
    path('schools/<int:pk>/category', views.category, name='categories'),
    path('schools/<int:pk>/section', views.section, name='sections'),
    path('schools/<int:pk>/reg_status', views.registration_status, name='registration-status'),
    path('schools/<int:pk>/access', views.access, name='accesses'),
    path('schools/<int:pk>/urban', views.rural_urban, name='rural-urban'),
    path('schools/<int:pk>/nearest_school', views.nearest_school, name='nearest-school'),
    path('schools/<int:pk>/nearest_deo', views.nearest_deo, name='nearest-deo'),
    path('schools/new/', SchoolCreateView.as_view(), name='new-school'),
    path('school/<int:pk>/details', SchoolDetailView.as_view(), name='school-details'),
    path('schools/<int:pk>/update/', SchoolUpdateView.as_view(), name='update-school'),
    path('schools/<int:pk>/facility/',FacilityCreateView.as_view(), name='new-facility'),
    path('schools/ownership/', OwnershipCreateView.as_view(), name='ownership'),
    path('schools/ownership/<int:pk>/update/', OwnershipUpdateView.as_view(), name='ownership-update'),
    path('schools/access/', AccessCreateView.as_view(), name='access'),
    path('schools/access/<int:pk>/update/', AccessUpdateView.as_view(), name='access-update'),
    path('schools/section/', SectionCreateView.as_view(), name='section'),
    path('schools/section/<int:pk>/update/', SectionUpdateView.as_view(), name='section-update'),
    path('schools/level/', LevelCreateView.as_view(), name='level'),
    path('schools/level/<int:pk>/update/', LevelUpdateView.as_view(), name='level-update'),
    path('schools/category/', CategoryCreateView.as_view(), name='category'),
    path('schools/category/<int:pk>/update/', CategoryUpdateView.as_view(), name='category-update'),
    path('schools/schtype/', SchtypeCreateView.as_view(), name='schtype'),
    path('schools/schtype/<int:pk>/update/', SchtypeUpdateView.as_view(), name='schtype-update'),
    path('schools/regstatus/', RegstatusCreateView.as_view(), name='regstatus'),
    path('schools/regstatus/<int:pk>/update/', RegstatusUpdateView.as_view(), name='regstatus-update'),
    path('schools/cennostatus/', CennostatusCreateView.as_view(), name='cennostatus'),
    path('schools/cennostatus/<int:pk>/update/', CennostatusUpdateView.as_view(), name='cennostatus-update'),
    path('schools/district/<int:pk>/update/', DistrictUpdateView.as_view(), name='district-update'),
    path('schools/district/', DistrictCreateView.as_view(), name='district'),
    path('schools/region/', RegionCreateView.as_view(), name='region'),
    path('schools/region/<int:pk>/update/', RegionUpdateView.as_view(), name='region-update'),
    # Facility related urls-----------------------------------------------------------------------------
    path('schools/factype/', FacilityTypeView.as_view(), name='factype'),
    path('schools/factype/<int:pk>/update/', FacilityTypeUpdateView.as_view(), name='factype-update'),
    path('schools/facstatus/', FacilityStatusView.as_view(), name='facstatus'),
    path('schools/facstatus/<int:pk>/update/', FacilityStatusUpdateView.as_view(), name='facstatus-update'),
    
    # Teacher related urls-----------------------------------------------------------------------------

    path('teachers/<int:pk>/region', views.region_teachers, name='region-teachers'),
    path('teachers/<int:pk>/non_teaching_staff', views.non_teaching_staff, name='non-teaching-staff'),
    path('teachers/<int:pk>/qualification', views.qualification_teachers, name='qualification-teachers'),
    path('teachers/<int:pk>/left_teachers', views.left_teachers, name='left-teachers'),
    path('teachers/<int:pk>/education', views.education_teachers, name='education-teachers'),
    path('teachers/', views.teachers, name='strack-teachers'),
    path('teachers/new/', TeacherCreateView.as_view(), name='new-teacher'),
    path('teachers/view/', TeacherListView.as_view(), name='view-teachers'),
    path('teachers/transfer/view/', TeacherTransferListView.as_view(), name='view-teacher-transfers'),
    path('teachers/<int:pk>/', TeacherDetailView.as_view(), name='teacher-details'),
    path('teachers/<int:pk>/update/', TeacherUpdateView.as_view(), name='update-teacher'),
    path('teachers/gender/', GenderCreateView.as_view(), name='gender'),
    path('teachers/gender/<int:pk>/update/', GenderUpdateView.as_view(), name='update-gender'),
    path('teachers/status/', TeacherStatusCreateView.as_view(), name='teacher-status'),
    path('teachers/status/<int:pk>/update/', TeacherStatusUpdateView.as_view(), name='update-teacher-status'),
    path('teachers/transfer/', TransferTeacherCreateView.as_view(), name='transfer-teacher'),
    path('teachers/transfer/<int:pk>/update/', TransferTeacherUpdateView.as_view(), name='update-transfer'),
    path('teachers/designation/', DesignationCreateView.as_view(), name='designation'),
    path('teachers/designation/<int:pk>/update/', DesignationUpdateView.as_view(), name='update-designation'),
    # DEO related urls-----------------------------------------------------------------------------
    path('DEOs/', views.deos, name='strack-deos'),
    path('DEOs/new/', DeoCreateView.as_view(), name='new-deo'),
    path('DEOs/view/', DeoListView.as_view(), name='view-deos'),
    path('DEOs/<int:pk>/', DeoDetailView.as_view(), name='deo-details'),
    path('DEOs/<int:pk>/update/', DeoUpdateView.as_view(), name='update-deo'),
    path('DEOs/transfer/', TransferDeoCreateView.as_view(), name='transfer-deo'),
    path('DEOs/transfer/<int:pk>/update/', TransferDeoUpdateView.as_view(), name='update-deo-transfer'),
    # Resource related urls-----------------------------------------------------------------------------
    path('resources/', views.resources, name='strack-resources'),
    path('resources/type/', ResourceTypeCreateView.as_view(), name='resource-type'),
    path('resources/type/<int:pk>/update/', ResourceTypeUpdateView.as_view(), name='update-resource-type'),
    path('resources/source/', ResourceSourceCreateView.as_view(), name='resource-source'),
    path('resources/source/<int:pk>/update/', ResourceSourceUpdateView.as_view(), name='update-resource-source'),
    path('resources/resource/', ResourceCreateView.as_view(), name='resource'),
    path('resources/resource/<int:pk>/', ResourceDetailView.as_view(), name='resource-details'),
    path('resources/view/', ResourceListView.as_view(), name='view-resources'),
    path('resources/resource/<int:pk>/update/', ResourceUpdateView.as_view(), name='update-resource'),
    path('resources/allocate/', AllocateResourceCreateView.as_view(), name='allocate-resource'),
    path('resources/allocate/view/', AllocateResourceListView.as_view(), name='allocated-resources'),
    path('resources/allocate/<int:pk>/update/', AllocateResourceUpdateView.as_view(), name='update-allocate-resource'),
    # Marketing related urls-----------------------------------------------------------------------------
    path('marketing/', views.marketing, name='strack-marketing'),
    path('marketing/new-product/', ProductCreateView.as_view(), name='product'),
    path('marketing/<int:pk>/update/', ProductUpdateView.as_view(), name='update-product'),
    path('marketing/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('marketing/user-products/', UserProducts.as_view(), name='user-products'),
    path('marketing/product-status/', ProductStatusCreateView.as_view(), name='product-status'),
    path('marketing/product-status/<int:pk>/update/', ProductStatusUpdateView.as_view(), name='update-product-status'),

    # Communication related urls-----------------------------------------------------------------------------
    path('communication/', views.communication, name='strack-communication'),
    # Settings related urls-----------------------------------------------------------------------------
    path('settings/', views.settings, name='strack-settings'),
    path('subjects/', SubjectCreateView.as_view(), name='subject'),
    path('subjects/<int:pk>/update/', SubjectUpdateView.as_view(), name='update-subject'),
]
