# Generated by Django 2.2.6 on 2019-11-06 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_type', models.CharField(max_length=45, verbose_name='Access Type')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_type', models.CharField(max_length=45, verbose_name='Category Type')),
            ],
        ),
        migrations.CreateModel(
            name='Cennostatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cns', models.CharField(max_length=45, verbose_name='Center No. Registration status')),
            ],
        ),
        migrations.CreateModel(
            name='Deo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Deo's Name")),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(default='default.png', upload_to='deo_photos')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('des_type', models.CharField(max_length=45, verbose_name='Designation')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_name', models.CharField(max_length=45, verbose_name='District Name')),
            ],
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('owner', models.IntegerField()),
                ('group', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FacilityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_status', models.CharField(max_length=45, verbose_name='Facility status')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(max_length=45, verbose_name='Facility Type')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=45, verbose_name='Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lev_name', models.CharField(max_length=45, verbose_name='Level')),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('own_type', models.CharField(max_length=45, verbose_name='Ownership Type')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('phone_contact', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(default='default.png', upload_to='product_photos')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_name', models.CharField(max_length=45, verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='Regstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rs_type', models.CharField(max_length=45, verbose_name='Registration status')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_source', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='School Name')),
                ('motto', models.CharField(max_length=100, verbose_name='School Motto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reg_no', models.CharField(max_length=100, verbose_name='Registration Number')),
                ('cen_no', models.CharField(max_length=100, verbose_name='Center Number')),
                ('yr_est', models.DateField(verbose_name='Year Established')),
                ('yr_reg', models.DateField(blank=True, null=True, verbose_name='Year of Registration')),
                ('yr_cnr', models.DateField(blank=True, null=True, verbose_name='Year of Center No. Registration')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('logo', models.ImageField(blank=True, default='default.png', null=True, upload_to='school_logos')),
                ('access', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.Access', verbose_name='School Access')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.Category', verbose_name='School Category')),
                ('cennostatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.Cennostatus', verbose_name='Center No. Registration status')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.District', verbose_name='District')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.Level', verbose_name='Hieghest Level')),
                ('ownership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.Ownership', verbose_name='Ownership')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.Region', verbose_name='Region')),
                ('regstatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.Regstatus', verbose_name='Registration status')),
            ],
        ),
        migrations.CreateModel(
            name='Schtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_type', models.CharField(max_length=45, verbose_name='School Type')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_type', models.CharField(max_length=45, verbose_name='Section')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Teacher's Name")),
                ('reg_no', models.CharField(blank=True, max_length=200, null=True, verbose_name='Registration Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_registered', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(default='default.png', upload_to='teacher_photos')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.District')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.Gender')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.Region')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_status', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TransferTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_valid', models.DateField(blank=True, null=True, verbose_name='Transfer Teacher Until')),
                ('date_transfered', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('designation', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='ministry.Designation')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.Teacher')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferDeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_valid', models.DateField(blank=True, null=True, verbose_name='Transfer Deo Until')),
                ('date_transfered', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('deo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.Deo')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.District')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='ministry.TeacherStatus', verbose_name='Teacher Status'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='school',
            name='schtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.Schtype', verbose_name='School Type'),
        ),
        migrations.AddField(
            model_name='school',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.Section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='school',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('year', models.DateField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(default='default.png', upload_to='teacher_photos')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.ResourceType')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.ResourceSource')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='ministry.ProductStatus', verbose_name='Product Status'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=45)),
                ('photo', models.ImageField(default='default.png', upload_to='fac_uploads')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('facility_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.FacilityType')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.FacilityStatus')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='deo',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.District'),
        ),
        migrations.AddField(
            model_name='deo',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.Gender'),
        ),
        migrations.AddField(
            model_name='deo',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.Region'),
        ),
        migrations.AddField(
            model_name='deo',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='ministry.TeacherStatus', verbose_name='Deo Status'),
        ),
        migrations.AddField(
            model_name='deo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AllocateResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('year', models.DateField(default=django.utils.timezone.now)),
                ('date_allocated', models.DateField(default=django.utils.timezone.now)),
                ('date_valid', models.DateField(default=django.utils.timezone.now)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.Resource')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
