# Generated by Django 2.2.6 on 2019-11-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0002_auto_20191125_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='yr_cnr',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of Center No. Registration'),
        ),
        migrations.AlterField(
            model_name='school',
            name='yr_est',
            field=models.IntegerField(verbose_name='Year Established'),
        ),
        migrations.AlterField(
            model_name='school',
            name='yr_reg',
            field=models.IntegerField(blank=True, null=True, verbose_name='Year of Registration'),
        ),
    ]
