# Generated by Django 2.2.6 on 2019-11-26 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0004_teacher_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferteacher',
            name='school_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='school_from', to='ministry.School'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transferteacher',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_to', to='ministry.School'),
        ),
    ]
