# Generated by Django 2.2.6 on 2019-11-26 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0005_auto_20191126_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current', to='ministry.School')),
                ('previous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous', to='ministry.School')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='ministry.Teacher')),
            ],
        ),
    ]
