# Generated by Django 2.2.6 on 2019-12-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0007_teacher_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocateresource',
            name='amount_allocated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allocateresource',
            name='quantity_allocated',
            field=models.IntegerField(default=0),
        ),
    ]
