# Generated by Django 3.0.6 on 2020-06-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0009_auto_20191203_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='acc_type',
            field=models.CharField(max_length=45, unique=True, verbose_name='Access Type'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_type',
            field=models.CharField(max_length=45, unique=True, verbose_name='Category Type'),
        ),
        migrations.AlterField(
            model_name='cennostatus',
            name='cns',
            field=models.CharField(max_length=45, unique=True, verbose_name='Center No. Registration status'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='des_type',
            field=models.CharField(max_length=45, unique=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='district',
            name='dis_name',
            field=models.CharField(max_length=45, unique=True, verbose_name='District Name'),
        ),
        migrations.AlterField(
            model_name='facilitystatus',
            name='facility_status',
            field=models.CharField(max_length=45, unique=True, verbose_name='Facility status'),
        ),
        migrations.AlterField(
            model_name='facilitytype',
            name='facility_type',
            field=models.CharField(max_length=45, unique=True, verbose_name='Facility Type'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(max_length=45, unique=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='level',
            name='lev_name',
            field=models.CharField(max_length=45, unique=True, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='own_type',
            field=models.CharField(max_length=45, unique=True, verbose_name='Ownership Type'),
        ),
        migrations.AlterField(
            model_name='productstatus',
            name='status',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='reg_name',
            field=models.CharField(max_length=45, unique=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='regstatus',
            name='rs_type',
            field=models.CharField(max_length=45, unique=True, verbose_name='Registration status'),
        ),
        migrations.AlterField(
            model_name='resourcesource',
            name='resource_source',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='resource_type',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.Level', verbose_name='Highest Level'),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, default='school_logos/default.png', null=True, upload_to='school_logos'),
        ),
        migrations.AlterField(
            model_name='schtype',
            name='sch_type',
            field=models.CharField(max_length=45, unique=True, verbose_name='School Type'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sec_type',
            field=models.CharField(max_length=45, unique=True, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default='teacher_photos/default.png', upload_to='teacher_photos'),
        ),
        migrations.AlterField(
            model_name='teacherstatus',
            name='teacher_status',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
