# Generated by Django 3.0.6 on 2020-08-10 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0012_auto_20200807_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='district',
        ),
        migrations.AddField(
            model_name='school',
            name='parish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.Parish'),
        ),
    ]
