# Generated by Django 3.0.6 on 2020-08-13 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0013_auto_20200810_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=45, unique=True)),
            ],
        ),
    ]
