# Generated by Django 3.0.6 on 2020-08-18 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0015_auto_20200818_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='reg_no',
        ),
        migrations.AddField(
            model_name='teacher',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.TeacherEducation'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_appointment',
            field=models.DateField(blank=True, null=True, verbose_name='Date of first appointment'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_posting',
            field=models.DateField(blank=True, null=True, verbose_name='Date of first posting'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='nin',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='payroll_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='previous_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_post', to='ministry.District'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.TeacherProfession'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='responsibilities',
            field=models.ManyToManyField(to='ministry.TeacherResponsibility'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='salary_scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.TeacherSalaryScale'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='surname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district', to='ministry.District'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
                ('subject_level', models.ManyToManyField(to='ministry.Level')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='specialization',
            field=models.ManyToManyField(related_name='specialization', to='ministry.Subject'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='taught',
            field=models.ManyToManyField(related_name='taught', to='ministry.Subject'),
        ),
    ]
