# Generated by Django 3.0.6 on 2020-08-18 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0017_auto_20200818_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.TeacherTraining'),
        ),
    ]
