# Generated by Django 3.0.6 on 2020-08-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0018_teacher_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, default='teacher_photos/default.png', null=True, upload_to='teacher_photos'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='responsibilities',
            field=models.ManyToManyField(blank=True, to='ministry.TeacherResponsibility'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialization',
            field=models.ManyToManyField(blank=True, related_name='specialization', to='ministry.Subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='taught',
            field=models.ManyToManyField(blank=True, related_name='taught', to='ministry.Subject'),
        ),
    ]
