# Generated by Django 3.0.6 on 2020-09-21 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0020_auto_20200826_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='TertiaryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TertiaryLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='tertiary_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.TertiaryCategory'),
        ),
        migrations.AddField(
            model_name='school',
            name='tertiary_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.TertiaryLevel'),
        ),
    ]
