# Generated by Django 3.0.6 on 2020-08-07 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0012_auto_20200807_0517'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.Class'),
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
