# Generated by Django 3.0.6 on 2020-08-13 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20200807_0517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
