# Generated by Django 3.0.6 on 2020-08-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20200811_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='no_of_students',
            new_name='boys',
        ),
        migrations.AddField(
            model_name='student',
            name='girls',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
