# Generated by Django 3.0.6 on 2020-08-13 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0014_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0004_agegroup_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrphanStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialNeedStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='requestresource',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ministry.School'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestteacher',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ministry.School'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolresource',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ministry.School'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolteacher',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ministry.School'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ministry.School'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agegroup',
            name='value',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='onpayroll',
            name='payroll',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='requestresource',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestteacher',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolresource',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolteacher',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schoolteacherstatus',
            name='status',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('school', 'class_name', 'age', 'year')},
        ),
        migrations.CreateModel(
            name='TransferedStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('girls', models.IntegerField(blank=True)),
                ('boys', models.IntegerField(blank=True)),
                ('year', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.Class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('school', 'class_name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='SpecialNeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('girls', models.IntegerField(blank=True)),
                ('boys', models.IntegerField(blank=True)),
                ('year', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.Class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SpecialNeedStatus')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('school', 'class_name', 'year', 'status')},
            },
        ),
        migrations.CreateModel(
            name='SeatingAndWritingSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('pupils', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.Class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('school', 'class_name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Repeater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('girls', models.IntegerField(blank=True)),
                ('boys', models.IntegerField(blank=True)),
                ('year', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.Class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('school', 'class_name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ProposedIntake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('girls', models.IntegerField(blank=True)),
                ('boys', models.IntegerField(blank=True)),
                ('year', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.Class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('school', 'class_name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='PhysicalStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('streams', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.Class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('school', 'class_name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Orphan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('girls', models.IntegerField(blank=True)),
                ('boys', models.IntegerField(blank=True)),
                ('year', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.Class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.OrphanStatus')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('school', 'class_name', 'year', 'status')},
            },
        ),
        migrations.CreateModel(
            name='NewEntrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('girls', models.IntegerField(blank=True)),
                ('boys', models.IntegerField(blank=True)),
                ('year', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.AgeGroup')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('school', 'age', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('girls', models.IntegerField(blank=True)),
                ('boys', models.IntegerField(blank=True)),
                ('year', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.Class')),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='ministry.Country')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('school', 'class_name', 'year', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('girls', models.IntegerField(blank=True)),
                ('boys', models.IntegerField(blank=True)),
                ('year', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.Class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Term')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('school', 'class_name', 'year')},
            },
        ),
    ]
