# Generated by Django 3.0.6 on 2020-08-12 13:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0013_auto_20200810_1008'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0004_auto_20200811_1647'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('user', 'class_name', 'age', 'year')},
        ),
    ]
