# Generated by Django 3.0.6 on 2020-08-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20200812_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='boys',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='girls',
            field=models.IntegerField(default=0),
        ),
    ]
