# Generated by Django 3.0.6 on 2020-08-17 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_intakeclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposedintake',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.IntakeClass'),
        ),
    ]
