# Generated by Django 3.0.6 on 2020-08-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20200812_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='boys',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='girls',
            field=models.IntegerField(blank=True),
        ),
    ]
