# Generated by Django 3.0.6 on 2020-08-20 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0019_auto_20200820_2135'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0008_auto_20200818_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers', models.IntegerField(blank=True)),
                ('year', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.Class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('school', 'class_name', 'year')},
            },
        ),
        migrations.CreateModel(
            name='NonTeachingStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.IntegerField(blank=True)),
                ('female', models.IntegerField(blank=True)),
                ('year', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('staff_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.StaffType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('school', 'staff_type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LeftTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.IntegerField(blank=True)),
                ('female', models.IntegerField(blank=True)),
                ('year', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Reason')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('school', 'reason', 'year')},
            },
        ),
    ]
