# Generated by Django 3.0.6 on 2020-08-24 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ministry', '0019_auto_20200820_2135'),
        ('school', '0009_leftteacher_nonteachingstaff_reason_stafftype_teacherallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceToMainWaterSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnergySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LatrineState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LatrineUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomCompletion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterAndEnergySource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('distance_to_water_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.DistanceToMainWaterSource')),
                ('energy_sources', models.ManyToManyField(to='school.EnergySource')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('water_sources', models.ManyToManyField(to='school.WaterSource')),
            ],
            options={
                'unique_together': {('school', 'year')},
            },
        ),
        migrations.CreateModel(
            name='UnderConstructionBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField(blank=True)),
                ('year', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('room_completion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.RoomCompletion')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('room_completion', 'school', 'year')},
            },
        ),
        migrations.CreateModel(
            name='NeededBuilding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField(blank=True)),
                ('year', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.RoomType')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('room_type', 'school', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Latrine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rooms', models.IntegerField(blank=True)),
                ('year', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.LatrineState')),
                ('use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.LatrineUse')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('state', 'use', 'school', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent', models.IntegerField(blank=True)),
                ('temporary', models.IntegerField(blank=True)),
                ('year', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('room_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.RoomState')),
                ('room_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.RoomStatus')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.RoomType')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ministry.School')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('room_status', 'room_type', 'room_state', 'school', 'year')},
            },
        ),
    ]
