# Generated by Django 3.0.6 on 2020-08-24 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_building_distancetomainwatersource_energysource_latrine_latrinestate_latrineuse_neededbuilding_roomc'),
    ]

    operations = [
        migrations.AddField(
            model_name='underconstructionbuilding',
            name='room_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school.RoomType'),
            preserve_default=False,
        ),
    ]
