# Generated by Django 3.0.6 on 2020-08-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0019_auto_20200820_2135'),
        ('school', '0011_underconstructionbuilding_room_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='underconstructionbuilding',
            unique_together={('room_type', 'room_completion', 'school', 'year')},
        ),
    ]
