# Generated by Django 3.0.6 on 2020-06-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20200629_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='apply',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=45, unique=True, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterUniqueTogether(
            name='apply',
            unique_together={('service', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='serviceprovider',
            unique_together={('service', 'email')},
        ),
    ]
