# Generated by Django 3.0.6 on 2020-06-29 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20200629_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
