# Generated by Django 3.0.6 on 2020-07-28 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0011_auto_20200723_1444'),
        ('public', '0008_auto_20200629_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ministry.District'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
