# Generated by Django 3.0.6 on 2020-08-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0016_auto_20200818_1534'),
        ('public', '0010_auto_20200813_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AlterField(
            model_name='lockdownpackage',
            name='subject',
            field=models.ManyToManyField(to='ministry.Subject'),
        ),
    ]
