# Generated by Django 3.0.6 on 2021-06-10 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='covid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
