from django.contrib import admin
from .models import *
from django.db import models
admin.site.register( SchoolTeacher )
admin.site.register( SchoolResource )
admin.site.register( SchoolTeacherStatus )
admin.site.register( OnPayroll )
admin.site.register( Student )
admin.site.register( RequestTeacher )
admin.site.register( RequestStatus )
admin.site.register( AgeGroup )
admin.site.register( Repeater )
admin.site.register( Nationality )
admin.site.register( ProposedIntake )
admin.site.register( PhysicalStream )
admin.site.register( Orphan )
admin.site.register( SpecialNeed )
admin.site.register( NewEntrant )
admin.site.register( SeatingAndWritingSpace )
admin.site.register( TransferedStudent )
admin.site.register( Examination )
admin.site.register( OrphanStatus )
admin.site.register( SpecialNeedStatus )
admin.site.register( Term )
admin.site.register( IntakeClass )